Revert "Add py as dependency to remeditate AttributeError: module 'py' has no attribute 'io' (#818)"
This reverts commit 465c3487a02f046e1b2e01fbefd69c61c2327f05.